-- // --------------------------- SQL --------------------------- \\ -- 

-----------------------------------------------------------------------
-- // ------------ GESTION DE LOS DATOS Y CONSULTAS ------------- \\ --
-----------------------------------------------------------------------

-------- CREAR UNA TABLA --------

CREATE TABLE NOMBRE_TABLA(
    CLAVE_PRIMARIA VARCHAR(7) PRIMARY KEY, -- VARCHAR será el tipo de dato que usaremos y con PRIMARY KEY LE ESTAREMOS INDICANDO QUE DICHO ATRIBUTO SERÁ CLAVE PRIMARIA
    ATRIBUTO NUMBER NOT NULL, -- Aqui le estamos indicando que el tipo de dato va a ser un numero y que no puede ser nulo
    ATRIBUTO_FECHA DATE DEFAULT '200100615 00:00:00.000', -- De esta manera indicamos que el archivo es de tipo fecha y que por defecto va a ser la fecha indicada
    ATRIBUTO2 NUMBER(4,2) CHECK (ATTRIBUTO2 BETWEEN 4000 AND 5000), -- Este atributo tendrá un numero hasta 9999 ya que solo podrá tener 4 digitos y 2 decimales, tambien checkeara que se introduzcan valores en dicho rango
);

-------- INSERTAR VALORES --------

INSERT INTO NOMBRE_TABLA (ATRIBUTO1, ATRIBUTO2, ATRIBUTO3) VALUES (VALOR1, 'VALOR2', 'VALOR3') -- Los strings van con comillas y los numeros sin ellas

-------- ELIMINAR UNA TABLA --------

DROP TABLE NOMBRE_TABLA
DROP TABLE NOMBRE_TABLA CASCADE CONSTRAINTS 
-- Borrar una tabla que tenga uniones con otras tablas y de error

-------- DESCRIBIR UNA TABLA --------

DESC NOMBRE TABLA 
-- Mostrará como esta construida

-------- MODIFICAR TABLAS --------

ALTER TABLE NOMBRE_TABLA
ADD(ATRIBUTO_NUEVO VARCHAR(5), ATRIBUTO_NUEVO NUMBER) 
-- De esta forma añadimos atributos

ALTER TABLE NOMBRE_TABLA
MODIFY ATRIBUTO NUMBER 
-- Modificamos un atributo que ya este en la tabla

ALTER TABLE NOMBRE_TABLA
DROP COLUMN ATRIBUTO 
-- Eiminar un atributo de una tabla

ALTER TABLE NOMBRE_TABLA
ADD CONSTRAINT NOMBRE_REGLA UNIQUE (ATRIBUTO) 
-- Añadimos una regla que haya que el atributo que indiquemos sea unico, es decir, que el registro no se pueda repetir

RENAME NOMBRE_TABLA TO NOMBRE_TABLA_NUEVO 
-- Cambiar el nombre a una tabla

COMMIT -->> RECUPERA DATOS DESDE ROLLBACK <<--
ROLLBACK -->> DESHACE LOS CAMBIOS HASTA COMMIT <<--

-------- BORRAR REGISTROS DE UNA COLUMNA --------

DELETE NOMBRE_TABLA
WHERE...

TRUNCATE TABLE NOMBRE_TABLA 
-- Elimina los valores igual que DELETE, a diferencia de que no podremos recuperar la informacion con un ROLLBACK

-------- CONSULTA - SELECT --------

SELECT * FROM NOMBRE_TABLA 
-- SIMPLE Extraeremos todos los registros de todos los atributos de la tabla que indiquemos.

SELECT ATRIBUTO1, ATRIBUTO2 FROM NOMBRE_TABLA 
-- Extraer los datos de uno o más atributos

SELECT ATRIBUTO1, ATRIBUTO2 FROM NOMBRE_TABLA 
WHERE [CONDICION]

SELECT ATRIBUTO1, ATRIBUTO2 FROM NOMBRE_TABLA 
WHERE [CONDICION] or [CONDICION]

SELECT ATRIBUTO1, ATRIBUTO2 FROM NOMBRE_TABLA 
WHERE [CONDICION] and [CONDICION]
-- Extraer los datos de uno o más atributos con condiciones

SELECT * FROM NOMBRE_TABLA 
GROUP BY ATRIBUTO1 
-- Usaremos group para agrupar registros con el mismo valor

SELECT * FROM NOMBRE_TABLA 
ORDER BY ATRIBUTO1 
-- Extraemos todos los datos de una tabla y los ordenamos por los resgistros del atributo que indiquemos
-- Por ejemplo, en un caso real, podríamos ordernar los datos por la edad, o salario...

SELECT DISTINCT ATRIBUTO FROM NOMBRE_TABLA
-- Al extraer los datos de la columna o atributo, si hay registros repetidos, solo los mostrará una vez

SELECT ATRIBUTO FROM NOMBRE_TABLA
UNION
SELECT ATRIBUTO FROM NOMBRE_TABLA2
-- Muestra los valores de dos tablas, una debajo de otra

SELECT ATRIBUTO FROM NOMBRE_TABLA
INTERSECT
SELECT ATRIBUTO FROM NOMBRE_TABLA2
-- Muestra unicamente los valores de dos tablas en los que haya coincidencia

SELECT ATRIBUTO FROM NOMBRE_TABLA
MINUS
SELECT ATRIBUTO FROM NOMBRE_TABLA2
-- Si hay un valor identido en ambas tablas, no los muestra, si se repite el mismo valor en la misma tabla, solo lo muestra una vez

SELECT PERSONAS.DNI, ARTICULOS.COD_ART
FROM PERSONAS,ARTICULOS, PER_ART
WHERE PERSONAS.DNI = PER_ART.DNI
AND PER_ART.COD_ART = ARTICULOS.COD_ART;
-- UNION DE TABLAS, IMPORTANTE CUANDO TENEMOS UN ATRIBUTO COMO CLAVE PRIMARIA EN UNA TABLA Y SECUNDARIA EN OTRA

SELECT APELLIDO, SALARIO, OFICIO, FECHA_ALT FROM EMPLEADOS
WHERE SALARIO >= (SELECT SALARIO FROM EMPLEADOS WHERE APELLIDO='MARTIN');
-- SUBCONSULTAS, extraeremos el salario similar al salario de los que se apelliden Martin

SELECT NOMBRE_DEPART, DEPT_NO FROM DEPARTAMENTOS
WHERE NOT EXISTS (SELECT * FROM EMPLEADOS WHERE EMPLEADOS.DEPT_NO = DEPARTAMENTOS.DEPT_NO); 
-- SACA DATOS CUANDO NO SE CUMPLE LA CONDICION DE QUE EL NUMERO DE DEPT DE EMPLEADOS SEA IGUAL AL NUMERO DEPT DE DEPARTAMENTOS <<--

SELECT NOMBRE_DEPART, DEPT_NO FROM DEPARTAMENTOS
WHERE EXISTS (SELECT * FROM EMPLEADOS WHERE EMPLEADOS.DEPT_NO = DEPARTAMENTOS.DEPT_NO);

SELECT * FROM  EMPLEADOS 
WHERE SALARIO = ANY (SELECT SALARIO FROM EMPLEADOS WHERE DEPT_NO=30)

SELECT * FROM EMPLEADOS  
WHERE SALARIO < ALL (SELECT SALARIO FROM EMPLEADOS WHERE DEPT_NO = 30)
-- Más ejemplos de SUBCONSULTAS

-------- FUNCIONES --------

SELECT COUNT (*) ARTICULOS; 
-- SABER CUANTAS UNIDADES DE DATOS TENEMOS 

SELECT COUNT(PESO) FROM ARTICULOS; 
-- CONTARIA DE TODOS ESOS DATOS CUANTOS TIENEN INFORMACION SOBRE EL PESO

SELECT SUM (PESO) FROM PERSONAS; 
-- SUMA TODOS LOS VALORES 

SELECT AVG (EDAD) FROM PERSONAS; 
-- SACA LA MEDIA 

SELECT MIN (PRECIO) FROM ARTICULOS; 
-- SACAR EL MINIMO 

SELECT MAX (PRECIO) FROM ARTICULOS 
-- SACAR EL VALOR MAXIMO DE UN ATRIBUTO DE UNA TABLA 

SELECT RTRIM (LTRIM (TITULO, '"'), '."') FROM MISTEXTOS;
-- SUSTITUIR STRINGS

SELECT REPLACE ('BLANCO Y NEGRO', 'O', 'AS') FROM DUAL;
-- Reemplazar de la primera String, la ocurrencia de la segunda String por la ocurrencia de la tercera

SELECT SUBSTR ('ASDASDAS', 3.2) "CAD1" FROM DUAL;
-- Extrae 2 caracteres a partir de la tercera pocision

SELECT TRANSLATE ('EL LIBRO DE LA SELVA', 'EL', 'el') FROM DUAL;

SELECT ASCII ('A') FROM DUAL;

SELECT INSTR ('II CAMPEONATO DE NATACION NACIONAL', 'NA' 3,2) FROM DUAL;

SELECT LENGTH ('CAMPEONATO DE NATACION NACIONAL') FROM DUAL;
--Nos muestra el tamaño de una String

SELECT UPPER (AUTOR), UPPER (TITULO) FROM LIBROS;
-- Convierte las palabras en mayusculas

SELECT LOWER (AUTOR), LOWER (TITULO) FROM LIBROS;
-- Convierte las palabras en minusculas

SELECT INITCAP (TITULO) FROM LIBROS; 
-- CONVIERTE LA PRIMERA LETRA DE CADA PALABRA EN MAYUSCULA 

SELECT LPAD (TITULO, 20, '*') FROM LIBROS;
-- Comparar valores

SELECT ProductID, ISNULL(Color, 'Sin color'), [Name] FROM Production.Product
-- Sustituir los valores NULL por lo que nosotros indiquemos

-----------------------------------------------------------------------
-- // ------------ ADMINISTRACION DE BASE DE DATOS  ------------- \\ --
-----------------------------------------------------------------------

CREATE TABLESPACE NOMBRE_TABLESPACE
DATAFILE 'G:\oracle11\oradata\orcl11\NOMBRE_TABLESPACE.DBF' SIZE 5M;
-- Crear un table space de un tamaño de 5 megas

CREATE TABLESPACE TS5
DATAFILE 'G:\oracle11\oradata\orcl11\DATAFILE5.DBF' SIZE 50M
BLOCKSIZE 2K;
-- CREAR UN TABLESPACE CON UN BLOCKSIZE DE 2 K*/

CREATE TABLESPACE TS6
DATAFILE 'G:\oracle11\oradata\orcl11\DATAFILE6.DBF' SIZE 50M
BLOCKSIZE 16K
AUTOEXTEND ON NEXT 120 K MAXIZE 1 M; 
-- CREAR UN TABLESPACE CON AUTOEXTEND

CREATE TABLESPACE TS8
DATAFILE 'G:\oracle11\oradata\orcl11\DATAFILE8.DBF' SIZE 10M
AUTOEXTEND ON NEXT 5 MAXSIZE 50M;
AUTOEXTEND ON NEXT 5 MAXSIZE UNLIMITED; 
-- CREAR UN TABLESPACE CON AUTOEXTEND ILIMITADO 

CREATE TABLESPACE TS7
DATAFILE 'G:\oracle11\oradata\orcl11\DATAFILE7.DBF' SIZE 10M
AUTOEXTEND OFF; 
-- CREAR UN TABLESPACE CON EL AUTOEXTEND APAGADO 

CREATE TABLESPACE TSTORAGE
DATAFILE 'G:\oracle11\oradata\orcl11\DATAFILE10.DBF' SIZE 15M
DEFAULT STORAGE (INITIAL 50K NEXT 300K MINEXTENTS 1 MAXEXTENTS 20); 
-- CREAR UN TABLESPACE CON ALMACENAMIENTO POR DEFECTO 

ALTER TABLE DAVID.PERSONAS MOVE TABLESPACE
TS9; 
-- MOVER UNA TABLA A UN DETERMINADO TABLESPACE 

DROP TABLESPACE TS1; 
-- ELIMINAR UN TABLESPACE 

ALTER USER HOLA
DEFAULT TABLESPACE TS9; 
-- ASIGNAR UN TABLESPSACE A UN USUARIO 

CREATE USER NOMBRE_USUARIO
IDENTIFIED BY 123456
DEFAULT TABLESPACE NOMBRE_TABLESPACE;
-- Creamos un usuario y le asignamos un table space en concreto

GRANT CONNECT TO NOMBRE_USUARIO;
GRANT RESOURCE TO NOMBRE_USUARIO;
-- Concedemos al usuario los permisos de conectarse a la base de datos y hacer procedimientos, schemas...

GRANT SELECT ANY TABLE TO NOMBRE_USUARIO;
-- Conceder permisos sobre cualquier tabla

GRANT CREATE TABLESPACE TO DAVID; 
--PERMITIR AL USUARIO CREAR TABLESPACES 

GRANT SELECT ON USUPRIV1.EMPLEADOS TO USUPRIV2; 
--DARLE PERMISOS DE CONSULTA  USUPRIV2 SOBRE LA TABLA DE EMPLEADOS DE USUPRIV1

REVOKE SELECT ON USUPRIV1.EMPLEADOS FROM USUPRIV2; 
-- QUITARLE LOS PERMISOS 

GRANT INSERT ON USUPRIV3.VIVIENDAS TO USUPRIV1 WITH GRANT OPTION;
-- DAR PERMISOS DE ADMIN

ALTER USER HOLA
QUOTA 2M ON TS9; 
--DARLE UNA QUOTA DE 2 MEGAS AL USUARIO HOLA EN EL TS9

RENAME USER HOLA TO ADIOS; 
-- CAMBIAR EL NOMBER A UN USUARIO

GRANT RESOURCE TO USUPRIV2 WITH ADMIN OPTION; 
-- PERMISOS DE CREAR OBJETOS CON OPCION DE ADMINSITRADOR 

CREATE ROLE GESTION IDENTIFIED BY 123456; 
-- CREAR UN ROL 

GRANT GESTION TO USUROL; 
-- ASIGNAR EL ROL AL USUARIO 

SET ROLE GESTION IDENTIFIED BY 123456; 
-- ACTIVAR EL ROL (NECESARIO)

ALTER USER USUROL DEFAULT ROLE NONE;
-- QUITARLE TODOS LOS ROLES A UN USUARIO 

REVOKE GESTION FROM USUROL;
-- QUITARLE UN ROL ESPECIFICO A UN USUARIO

CREATE PROFILE USUPERFIL LIMIT 
SESSIONS_PER_USER 2;
-- CREAR UN PERFIL_ SE USA PARA AÑADIR RESTRICCIONES A USUARIOS 

ALTER USER USUPERFIL1 PROFILE USUPERFIL; 
-- ASIGNAR UN USUARIO CON UN PERFIL
